Traceback (most recent call last):
  File "Loinnir.py", line 124, in <module>
    env = sys.argv[2]
IndexError: list index out of range
Traceback (most recent call last):
  File "Loinnir.py", line 124, in <module>
    env = sys.argv[2]
IndexError: list index out of range
